name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    env:
      scheme: TestApp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine iOS Simulator destination
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          echo "device=$device" >> $GITHUB_ENV

      - name: Build
        run: |
          xcodebuild build-for-testing -scheme "$scheme" -destination "platform=$platform,name=$device"

      - name: Test
        run: |
          xcodebuild test-without-building -scheme "$scheme" -destination "platform=$platform,name=$device"
